### ISSUE TITLE
Black borders on youtube thumbnails

### ISSUE THREAD

**Issue by synox** [hlxsites/zemax#153]
Issue: 
![Screenshot 2023-05-17 at 17 06 51](https://github.com/hlxsites/zemax/assets/2250964/c0e467ad-2d43-4553-aa9c-568d24715a5e)

## Possible solution: 
 - move border-radius to parent and hide overflow: 
 ```css
.cards.video .cards-card-image {
    border-top-left-radius: 16px;
    border-top-right-radius: 16px;
    overflow: hidden;
}
```
- zoom the thumbnail by 10% and remove the border radius: 
```css
.cards > ul > li img {
    transform: scale(1.1);
```
- maybe restrict this youtube videos, by only zooming youtube thumbnails: 
```css
.cards > ul > li img[src*="img.youtube.com"] {
  transform: scale(1.1);
}
```
